import { decimalString, decimalUnits, resourceIdentity, type Observation } from "./ingestion";

export function percentile(values: number[], p: number): number { if(!values.length) throw new Error("Percentile needs observations");const sorted=[...values].sort((a,b)=>a-b);return sorted[Math.max(0,Math.ceil(p*sorted.length)-1)]; }
export function median(values: bigint[]): bigint {if(!values.length) throw new Error("Median needs observations");const sorted=[...values].sort((a,b)=>a<b?-1:a>b?1:0);const n=sorted.length;return n%2 ? sorted[Math.floor(n/2)] : (sorted[n/2-1]+sorted[n/2])/BigInt(2);}
export type Finding = {
  identityKey:string; resourceId:string; type:"idle_compute"|"unattached_storage"|"overprovisioned_compute"|"consumption_spike";
  severity:"high"|"medium";ruleVersion:string;evidence:Record<string,unknown>;thresholds:Record<string,unknown>;explanation:string;
  windowStart:string;windowEnd:string;financialInputs:Record<string,unknown>;projectedImpact:string|null;currency:string;
  impactKind:"confirmed_avoidable_waste"|"potential_spike_excess";status:"detected";
};
export type DetectionFinding = Finding;
function rate(row: Observation): bigint|null {if(row.interval_cost !== null) return decimalUnits(row.interval_cost)*BigInt(3600)/BigInt(Math.round(row.interval_hours*3600));if(row.hourly_rate !== null) return decimalUnits(row.hourly_rate);if(row.resource_type === "block_storage" && row.metadata.monthly_rate_per_gib !== undefined && row.metadata.storage_gib !== undefined) return decimalUnits(row.metadata.monthly_rate_per_gib)*BigInt(Math.round(row.metadata.storage_gib*1000000))/BigInt(1000000)/BigInt(720);return null;}
function weightedP95(group:Observation[],key:"cpu_percent"|"memory_percent"):number|null {if(group.some(r=>r[key]===null))return null;const sorted=[...group].sort((a,b)=>a[key]!-b[key]!);const total=group.reduce((sum,r)=>sum+Math.round(r.interval_hours*3600),0);let cumulative=0;for(const r of sorted){cumulative+=Math.round(r.interval_hours*3600);if(cumulative>=total*0.95)return r[key];}return sorted[sorted.length-1][key];}
export function detectFindings(observations: Observation[]): Finding[] {
  const groups=new Map<string,Observation[]>();for(const r of observations){const key=resourceIdentity(r)+r.currency;groups.set(key,[...(groups.get(key)??[]),r]);}
  const findings:Finding[]=[];
  for(const group of groups.values()) {
    group.sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp));const latest=group[group.length-1];
    const start=Date.parse(group[0].timestamp), end=Date.parse(latest.timestamp)+latest.interval_hours*3600000;
    let covered=0,lastEnd=start;for(const r of group){const s=Date.parse(r.timestamp),e=s+r.interval_hours*3600000;covered+=Math.max(0,e-Math.max(s,lastEnd));lastEnd=Math.max(lastEnd,e);}
    const adequate=end-start>=24*3600000 && covered/(end-start)>=0.9 && group.length>=2;
    const cpu=weightedP95(group,"cpu_percent");
    const memory=weightedP95(group,"memory_percent");
    const current=rate(latest);const priceSource=latest.metadata.pricing_source ?? "uploaded log (unverified)";
    const projection=(type:Finding["type"],hourly:bigint|null)=>{if(hourly===null)return null;if(type==="overprovisioned_compute" && latest.interval_cost!==null && latest.metadata.eligible_replacement_rate!==undefined){const seconds=BigInt(Math.round(latest.interval_hours*3600));const difference=decimalUnits(latest.interval_cost)*BigInt(3600)-decimalUnits(latest.metadata.eligible_replacement_rate)*seconds;return decimalString((difference>BigInt(0)?difference:BigInt(0))*BigInt(720)/seconds);}if(type!=="consumption_spike"&&type!=="overprovisioned_compute"){if(latest.interval_cost!==null)return decimalString(decimalUnits(latest.interval_cost)*BigInt(3600)*BigInt(720)/BigInt(Math.round(latest.interval_hours*3600)));if(latest.hourly_rate===null&&latest.metadata.monthly_rate_per_gib!==undefined&&latest.metadata.storage_gib!==undefined)return decimalString(decimalUnits(latest.metadata.monthly_rate_per_gib)*BigInt(Math.round(latest.metadata.storage_gib*1000000))/BigInt(1000000));}return decimalString(hourly*BigInt(720));};
    const add=(type:Finding["type"], hourly:bigint|null, explanation:string, evidence:Record<string,unknown>, thresholds:Record<string,unknown>, inputs:Record<string,unknown>, from=group[0].timestamp,to=new Date(end).toISOString(),projectedOverride?:string)=>findings.push({identityKey:resourceIdentity(latest),resourceId:String(latest.raw.resource_id ?? latest.resource_id),type,severity:type === "consumption_spike"?"high":"medium",ruleVersion:"cloudsentry-3.1",evidence,thresholds,explanation,windowStart:from,windowEnd:to,financialInputs:{...inputs,projectionHours:720,pricingSource:priceSource},projectedImpact:projectedOverride ?? projection(type,hourly),currency:latest.currency,impactKind:type === "consumption_spike"?"potential_spike_excess":"confirmed_avoidable_waste",status:"detected"});
    const coverage={observationCount:group.length,coveredHours:covered/3600000,spanHours:(end-start)/3600000,coverageRatio:covered/(end-start),cpuP95:cpu,memoryP95:memory};
    if(adequate && latest.resource_type === "compute" && group.every(r=>r.state === "running") && cpu !== null && memory !== null){
      if(cpu<5 && memory<10) add("idle_compute",current,"Running compute has CPU p95 below 5% and memory p95 below 10% across sufficient coverage. Projected avoidable cost is an estimate.",coverage,{cpuP95Below:5,memoryP95Below:10,minimumSpanHours:24,minimumCoverage:0.9},{currentHourlyRate:current === null?null:decimalString(current)});
      else if(cpu<20 && memory<40){const replacement=latest.metadata.eligible_replacement_rate === undefined?null:decimalUnits(latest.metadata.eligible_replacement_rate);const saving=current !== null && replacement !== null?(current>replacement?current-replacement:BigInt(0)):null;add("overprovisioned_compute",saving,"Compute utilization suggests over-provisioning. Savings require a documented eligible replacement rate and remain projected estimates.",coverage,{cpuP95Below:20,memoryP95Below:40,minimumSpanHours:24,minimumCoverage:0.9},{currentHourlyRate:current === null?null:decimalString(current),replacementHourlyRate:replacement === null?null:decimalString(replacement),replacementPricingSource:latest.metadata.replacement_pricing_source ?? (replacement === null?null:"uploaded log (unverified)")});}
    }
    if(adequate && latest.resource_type === "block_storage" && group.every(r=>r.state === "unattached" && r.attachment_count === 0)) add("unattached_storage",current,"Storage explicitly has no attachments throughout the qualifying window. The projection estimates avoidable cost.",coverage,{minimumSpanHours:24,minimumCoverage:0.9,attachmentCount:0},{currentHourlyRate:current === null?null:decimalString(current),storageGiB:latest.metadata.storage_gib ?? null,monthlyRatePerGiB:latest.metadata.monthly_rate_per_gib ?? null});
    if(latest.currency === "USD" && latest.interval_hours === 1 && latest.interval_cost !== null){
      const preceding:Observation[]=[];let next=Date.parse(latest.timestamp);for(let i=group.length-2;i>=0;i--){const r=group[i];if(r.interval_hours !== 1 || r.interval_cost === null || Date.parse(r.timestamp)+3600000 !== next) break;preceding.unshift(r);next=Date.parse(r.timestamp);}
      if(preceding.length>=6){const sorted=preceding.map(r=>decimalUnits(r.interval_cost!)).sort((a,b)=>a<b?-1:a>b?1:0), n=sorted.length;const doubledMedian=n%2?sorted[Math.floor(n/2)]*BigInt(2):sorted[n/2-1]+sorted[n/2];const cost=decimalUnits(latest.interval_cost),doubledExcess=cost*BigInt(2)-doubledMedian,excess=doubledExcess/BigInt(2);const halfString=(value:bigint)=>decimalString(value/BigInt(2))+(value%BigInt(2)?"5":"");if(cost*BigInt(2)>doubledMedian*BigInt(3) && doubledExcess>=BigInt(200000000)) add("consumption_spike",excess,"Latest hourly cost exceeds three times the median of preceding contiguous hourly costs with at least $1/hour increase. This is potential excess spend, not confirmed avoidable waste.",{baselineObservationCount:preceding.length,baselineHourlyCost:halfString(doubledMedian),latestHourlyCost:decimalString(cost)},{multipleStrictlyAbove:3,minimumBaselineIntervals:6,minimumAbsoluteIncrease:"1.00000000",thresholdCurrency:"USD"},{baselineHourlyCost:halfString(doubledMedian),latestHourlyCost:decimalString(cost),excessHourlyCost:halfString(doubledExcess)},preceding[0].timestamp,new Date(end).toISOString(),decimalString(doubledExcess*BigInt(720)/BigInt(2)));}
    }
  }
  return findings;
}
export function summarizeFindings(findings:Finding[]) {const currencies:Record<string,{confirmedAvoidableWaste:string;potentialSpikeExcess:string;unpricedFindings:number}>={};for(const f of findings){const entry=currencies[f.currency]??={confirmedAvoidableWaste:"0.00000000",potentialSpikeExcess:"0.00000000",unpricedFindings:0};if(f.projectedImpact === null) entry.unpricedFindings++;else {const key=f.impactKind === "potential_spike_excess"?"potentialSpikeExcess":"confirmedAvoidableWaste";entry[key]=decimalString(decimalUnits(entry[key])+decimalUnits(f.projectedImpact));}}return currencies;}
