import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { parseUpload } from "../src/lib/ingestion";
import { detectFindings, percentile, median, summarizeFindings } from "../src/lib/detection";
function rows(overrides:Record<string,unknown>={}, count=24){return parseUpload(JSON.stringify(Array.from({length:count},(_,i)=>({provider:"aws",account_id:"123456789012",region:"us-east-1",resource_id:"i-0123456789abcdef0",resource_type:"compute",timestamp:new Date(Date.UTC(2026,9,8,i)).toISOString(),interval_hours:1,cpu_percent:1,memory_percent:2,state:"running",hourly_rate:"0.20",interval_cost:"0.20",currency:"USD",...overrides}))),"json").observations;}
test("Verified demonstration produces $1296 potential spike excess in both formats",()=>{for(const format of ["csv","json"] as const){const f=detectFindings(parseUpload(readFileSync(`public/fixtures/demo-cloud-spike.${format}`,"utf8"),format).observations);assert.equal(f.length,1);assert.equal(f[0].type,"consumption_spike");assert.equal(f[0].projectedImpact,"1296.00000000");assert.equal(f[0].impactKind,"potential_spike_excess");}});
test("All waste classifications and idle exclusion prevent double counting",()=>{assert.deepEqual(detectFindings(rows()).map(f=>f.type),["idle_compute"]);assert.equal(detectFindings(rows())[0].projectedImpact,"144.00000000");const over=detectFindings(rows({cpu_percent:10,memory_percent:20,metadata:{eligible_replacement_rate:"0.10"}}));assert.equal(over[0].type,"overprovisioned_compute");assert.equal(over[0].projectedImpact,"72.00000000");assert.equal(detectFindings(rows({resource_type:"block_storage",state:"unattached",attachment_count:0}))[0].type,"unattached_storage");assert.equal(detectFindings(rows({cpu_percent:10,memory_percent:20}))[0].projectedImpact,null);});
test("Insufficient, missing and boundary metrics never become idle",()=>{assert.equal(detectFindings(rows({},23)).length,0);assert.equal(detectFindings(rows({cpu_percent:null})).length,0);assert.equal(detectFindings(rows({cpu_percent:20})).length,0);assert.equal(detectFindings(rows({memory_percent:40})).length,0);assert.equal(detectFindings(rows({cpu_percent:5,memory_percent:10}))[0].type,"overprovisioned_compute");assert.equal(detectFindings(rows({state:null})).length,0);assert.equal(detectFindings(rows({resource_type:"block_storage",state:"unattached",attachment_count:null})).length,0);});
test("Spike strict multiple, absolute threshold, zero baseline, currency and gaps",()=>{const spike=(baseline:string,latest:string,currency="USD")=>{const r=rows({interval_cost:baseline,currency},7);r[6].interval_cost=latest;return detectFindings(r);};assert.equal(spike("1","3").length,0);assert.equal(spike("0.10","1.09").length,0);assert.equal(spike("0","1")[0].projectedImpact,"720.00000000");assert.equal(spike("0.20","2","EUR").length,0);const gap=rows({},7);gap[6].timestamp="2026-10-08T09:00:00.000Z";gap[6].interval_cost="2";assert.equal(detectFindings(gap).length,0);});
test("Percentile nearest rank, median even and odd, currency-separated sums",()=>{assert.equal(percentile([1,2,3,4,5],0.95),5);assert.equal(median([BigInt(1),BigInt(4)]),BigInt(2));assert.equal(median([BigInt(9),BigInt(1),BigInt(4)]),BigInt(4));const usd=detectFindings(rows()),eur=detectFindings(rows({currency:"EUR"}));const totals=summarizeFindings([...usd,...eur]);assert.equal(totals.USD.confirmedAvoidableWaste,"144.00000000");assert.equal(totals.EUR.confirmedAvoidableWaste,"144.00000000");});
test("90 percent coverage boundary and monthly GiB evidence",()=>{const r=rows();r.splice(4,2);assert.equal(detectFindings(r)[0].type,"idle_compute");r.splice(4,1);assert.equal(detectFindings(r).length,0);const monthly=rows({resource_type:"block_storage",state:"unattached",attachment_count:0,hourly_rate:null,interval_cost:null,metadata:{storage_gib:100,monthly_rate_per_gib:"0.10",pricing_source:"Synthetic GiB-month price"}});assert.equal(detectFindings(monthly)[0].projectedImpact,"10.00000000");});
test("Long high utilization intervals dominate weighted p95; zero storage is valid",()=>{const r=rows({},23);const last={...r[22],timestamp:"2026-10-08T23:00:00.000Z",interval_hours:168,cpu_percent:90,memory_percent:90};assert.equal(detectFindings([...r,last]).length,0);const free=rows({resource_type:"block_storage",state:"unattached",attachment_count:0,hourly_rate:"0",interval_cost:"0"});assert.equal(detectFindings(free)[0].projectedImpact,"0.00000000");});
test("Half-unit even medians do not round a sub-dollar spike into qualification",()=>{const r=rows({},7);for(let i=0;i<6;i++)r[i].interval_cost=i<3?"0":"0.00000001";r[6].interval_cost="1.00000000";assert.equal(detectFindings(r).length,0);r[6].interval_cost="2.00000000";const f=detectFindings(r)[0];assert.equal(f.financialInputs.baselineHourlyCost,"0.000000005");assert.equal(f.financialInputs.excessHourlyCost,"1.999999995");assert.equal(f.projectedImpact,"1439.99999640");});
