import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { assertDecisionTransition, assertSimulationTransition, generateRemediation, RemediationError, type RemediationTarget } from "../src/lib/remediation-scripts";
const aws:RemediationTarget={provider:"aws",accountScope:"123456789012",region:"us-east-1",type:"compute",externalId:"i-0123456789abcdef0",rule:"consumption_spike",metadata:{}};
test("Executable AWS script defaults to stop and refuses deletion without both exact confirmations",()=>{
  const bash=process.platform==="win32"?"C:/Program Files/Git/bin/bash.exe":"/bin/bash";
  assert.ok(existsSync(bash),"Bash is required for the script safety check");
  const directory=mkdtempSync(join(tmpdir(),"cloudsentry-script-"));
  try{
    const path=join(directory,"verify.sh");
    // A shell function intercepts every AWS invocation. No cloud CLI can run.
    const stub=`aws() {\n case "$1 $2" in\n 'sts get-caller-identity') echo '123456789012';;\n 'ec2 describe-instances') echo 'running';;\n 'ec2 stop-instances') echo "MOCK_STOP:$*";;\n 'ec2 terminate-instances') echo "MOCK_DELETE:$*";;\n *) echo 'Unexpected mock invocation'; return 1;;\n esac\n}\n`;
    writeFileSync(path,generateRemediation(aws,"bash").scriptText.replace('#!/usr/bin/env bash\n',`#!/usr/bin/env bash\n${stub}`));
    const run=(args:string[],input:string)=>spawnSync(bash,[path,...args],{input,encoding:"utf8"});
    const stopped=run([],`${aws.externalId}\n`);assert.equal(stopped.status,0,stopped.stderr);assert.match(stopped.stdout,/MOCK_STOP/);assert.doesNotMatch(stopped.stdout,/MOCK_DELETE/);
    const deleted=run(["--delete"],`${aws.externalId}\nDELETE ${aws.externalId}\n`);assert.equal(deleted.status,0,deleted.stderr);assert.match(deleted.stdout,/MOCK_DELETE/);assert.match(deleted.stdout,/--region us-east-1 --instance-ids i-0123456789abcdef0/);assert.doesNotMatch(deleted.stdout,/MOCK_STOP/);
    for(const [args,input] of [[['--delete'],`${aws.externalId}\nwrong\n`],[['--delete'],`wrong\nDELETE ${aws.externalId}\n`],[['--unknown'],`${aws.externalId}\n`]] as [string[],string][]){const refused=run(args,input);assert.notEqual(refused.status,0);assert.doesNotMatch(refused.stdout,/MOCK_(STOP|DELETE)/);}
  }finally{rmSync(directory,{recursive:true});}
});
test("AWS fixture generation preserves exact target and deterministic hash with account preflight",()=>{const script=generateRemediation(aws,"bash");assert.equal(script.action,"stop_compute_or_explicit_delete");assert.ok(script.scriptText.includes("i-0123456789abcdef0"));assert.ok(script.scriptText.includes("get-caller-identity"));assert.ok(script.scriptText.includes("stop-instances"));assert.ok(script.scriptText.includes("read -r answer"));assert.equal(script.scriptHash,createHash("sha256").update(script.scriptText).digest("hex"));assert.equal(script.scriptHash,generateRemediation(aws,"bash").scriptHash);});
test("All supported provider compute/storage scripts have exact scopes and live attachment preflights",()=>{const awsDisk=generateRemediation({...aws,type:"block_storage",rule:"unattached_storage",externalId:"vol-0123456789abcdef0"},"bash");assert.ok(awsDisk.scriptText.includes("IRREVERSIBLE"));assert.ok(awsDisk.scriptText.includes("length(Volumes[0].Attachments)"));const subscription="12345678-1234-1234-1234-123456789012";const azure:RemediationTarget={...aws,provider:"azure",accountScope:subscription,region:"eastus",externalId:`/subscriptions/${subscription}/resourceGroups/demo/providers/Microsoft.Compute/virtualMachines/demo-vm`};assert.ok(generateRemediation(azure,"bash").scriptText.includes("az vm deallocate"));assert.ok(generateRemediation({...azure,type:"block_storage",rule:"unattached_storage",externalId:azure.externalId.replace("virtualMachines/demo-vm","disks/demo-disk")},"bash").scriptText.includes("managedByExtended"));const gcp:RemediationTarget={...aws,provider:"gcp",accountScope:"demo-project",region:"us-central1",externalId:"projects/demo-project/zones/us-central1-a/instances/demo-vm",metadata:{zone:"us-central1-a"}};assert.ok(generateRemediation(gcp,"bash").scriptText.includes('instances stop "$NAME"'));assert.ok(generateRemediation({...gcp,type:"block_storage",rule:"unattached_storage",externalId:gcp.externalId.replace("instances/demo-vm","disks/demo-disk")},"bash").scriptText.includes("value(users)"));});
test("Missing/unsafe identity metadata and invented Terraform are refused",()=>{for(const t of [{...aws,externalId:"i-good;rm -rf /"},{...aws,accountScope:"wrong"},{...aws,region:"us-east-1\nwhoami"},{...aws,provider:"gcp" as const,accountScope:"demo-project",region:"us-central1",externalId:"demo-vm"},{...aws,rule:"overprovisioned_compute"}])assert.throws(()=>generateRemediation(t,"bash"),RemediationError);assert.throws(()=>generateRemediation(aws,"terraform"),RemediationError);assert.throws(()=>generateRemediation({...aws,metadata:{terraform_address:"aws_instance.demo"}},"terraform"),RemediationError);});
test("Terraform only quotes supplied exact existing address and configuration with no apply/destroy",()=>{const script=generateRemediation({...aws,metadata:{terraform_address:"module.demo.aws_instance.vm",original_configuration:{instance_type:"t3.small"}}},"terraform");assert.ok(script.scriptText.includes("module.demo.aws_instance.vm"));assert.ok(script.scriptText.includes("t3.small"));assert.ok(!script.scriptText.split("\n").some(line=>/^(?!#).*terraform (apply|destroy)/.test(line)));assert.deepEqual(script.originalConfiguration,{instance_type:"t3.small"});});
test("Decisions and simulation require pending/approved state and exact immutable reviewed hash",()=>{const hash=generateRemediation(aws,"bash").scriptHash;assert.equal(assertDecisionTransition("pending_approval",hash,hash,"approve"),"approved");assert.equal(assertDecisionTransition("pending_approval",hash,hash,"reject"),"rejected");for(const status of ["approved","rejected","simulated_succeeded"])assert.throws(()=>assertDecisionTransition(status,hash,hash,"approve"),RemediationError);assert.throws(()=>assertDecisionTransition("pending_approval",hash,"0".repeat(64),"approve"),RemediationError);assert.equal(assertSimulationTransition("approved",hash,hash,hash),"simulated_succeeded");for(const status of ["pending_approval","rejected","simulated_succeeded"])assert.throws(()=>assertSimulationTransition(status,hash,hash,hash),RemediationError);assert.throws(()=>assertSimulationTransition("approved",hash,hash,null),RemediationError);assert.throws(()=>assertSimulationTransition("approved",hash,"0".repeat(64),hash),RemediationError);});
